export { ClaudeLLM } from './llm/claude';
export type { GeneratePatchOptions } from './llm/claude';
export { getPromptTemplate, detectChangeType } from './prompts/templates';
export type { PromptTemplate } from './prompts/templates';
export { ASTParser } from './ast/parser';
export type { ParsedFunction, ParsedFile } from './ast/parser';
export { PythonParser } from './ast/python-parser';
export { DiffEngine } from './ast/differ';
export type { StructuredDiff, ModifiedFunction } from './ast/differ';
export { CodeEmbedder, InMemoryVectorStore } from './embedding/embedder';
export type { CodeEmbedding, EmbeddingProvider, VectorStore, EmbeddingSearchResult } from './embedding/embedder';
export { CodeMapper } from './mapping/mapper';
export type { CodeMapping, MappingResult } from './mapping/mapper';
export { ConflictDetector } from './conflict/detector';
export type { ConflictRisk, ConflictReport, ConflictType } from './conflict/detector';
export { ConflictResolver } from './conflict/resolver';
export type { Resolution, ResolutionStrategy, ResolverOptions } from './conflict/resolver-types';
export { FeedbackCollector, FewShotRetriever, PromptPersonalizer } from './feedback';
export type { FeedbackRecord, FeedbackStats, FewShotExample } from './feedback';
export { KnowledgeGraph } from './knowledge';
export type { CodeNode, CodeEdge, DriftResult, UnsyncedChange } from './knowledge';
export { QualityAnalyzer } from './quality';
export type { ProjectFiles } from './quality';
export type { ConsistencyScore, QualityDiff, TechDebtItem, QualityReport } from './quality';
